<?php
require_once( "../globals/globals.inc.php" );
?>

<html><head><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"><base href="<?php print( LS_BASE_HREF );?>"><title>Scenes of Seduction: An Introduction</title><style type="text/css">
@import "scenes.css";

</style></head><body><div id="body"><div class="article"><p class="icons"></p>
<h1>Scenes of Love and Seduction</h1>
<h2>General Introduction</h2>
<p class="intro">Love and seduction are ageless themes, but the conventions which rule in every era reflect the cultural practices and sexual mores of the times.  With the exception of a few underground publications, the written records of love and seduction in the popular fiction and the popular press of the nineteenth century were exclusively heterosexual (homosexuality was illegal, as was interracial marriage) and largely middle and upper class in their class representations. Morality dramas were usually built around the stories of women who had once been respectable but lost their status through sins such as pregnancy out of wedlock or adultery after they had married, or else around innocent young maidens who came to the city and could not live without sinking into prostitution.  The scandals in the popular press expand our understanding of the practices of love and seduction beyond the refinements typically in force in literary and artistic representations.  Men who broke promises to marry, women duped by declarations of intent, men who harassed the maids, women who enticed men into promises, clergymen who seduced members of the congregation, and unwanted pregnancies were frequent causes for lawsuits.  Press coverage of such stories indicate the high level of interest middle-class readers took in such gossip.  
</p>
<p class="intro">When novels began in the eighteenth century in epistolary forms, many of them told tales of seduction.  <em>Pamela</em> and <em>Clarissa</em> are two such examples. These seductions were almost uniformly cast in terms of good and evil, though the naivete of the woman being seduced by the salacious and worldly man often made her a pathetic figure.  By the 1850's, literary tales of love and seduction became in some cases more morally complicated; for instance, portraits of unhappy marriages were possible.  Some depictions of seduction and romance were increasingly risque.  The changing conventions about sexual behavior produced a more physically permissive representation of romantic love than the earlier novels of seduction had allowed.</p>

<p class="intro">Just how much affection could one show in mid-nineteenth-century courtship?  When were love trysts within bounds and when were they out?  The mid-Victorian woman had to know the mores of love in a carriage, a garden, a parlor, a country lane, a hay field, a park, on a horse, on a picnic, in church, by the beach, in the barn, and behind the barn.  And she needed to know the kind of man, too.  Older men were safer than young ones, members of one's own class were less likely to take advantage than men from a higher class who might not consider marriage.  Sportsmen were riskier than farmers, and all of them were better than soldiers.</p>

<p class="intro">The codes which governed love and seduction were elaborate, and the consequences for breaking those codes could be ruinous.  With no sure forms of birth control, sex outside of marriage was a grave risk for a woman.  When conventions dictated that an implied intimacy would be interpreted as conveying an intent to marry, a man had to be careful what signals he gave, or he could find himself trapped into an engagement he never intended.  Yet, for all the rigidities of the conventions, people found ways to declare love, to propose, to seduce, and even to bear illegitimate children.  The documents in this section show us the complexities of the conventions, the ways lovers found to evade those conventions, and the many romances and scandals that arose in an era we mistakenly think of as being very reserved about sex.
</p>
<div id="footer"><a href="mailto:cdrh@unl.edu"><strong>Comments??</strong></a> &#160;| <a href="<?php print( $NCSMODS_BASE_HREF );?>">Project Homepage <img src="images/home.gif" /></a></div>
</div><div id="related"><p></p></div></div><div id="menu"><img alt="19th Century Studies: Scenes of Love and Seduction" src="images/bigtest.jpg"><ul><li><a href="index.php">Home</a></li><li><a href="introduction.php">Introduction</a></li><li><img alt="Contexts and Themes" src="images/context.gif"></li><li><a href="explore/settings.php">Spatial Setting</a></li><li><a href="explore/themes.php">Theme</a></li><li><img alt="Browse by content type" src="images/content.gif"></li><li><a href="explore/genres.php?name=fiction">Literature&nbsp;<img alt="Fiction" src="images/fiction.gif"></a></li><li><a href="explore/genres.php?name=image">Art &amp; Illustration&nbsp;<img alt="Art and Illustration" src="images/image.gif"></a></li><li><a href="explore/genres.php?name=history">History&nbsp;<img alt="History" src="images/history.gif"></a></li><li><a href="explore/genres.php?name=commentary">Commentary&nbsp;<img alt="Commentary" src="images/commentary.gif"></a></li></ul><form action="search/search.php"><p class="search"><a href="search/index.php"><img alt="Search" src="images/search.gif">SEARCH</a><br><br><input name="keyword" id="keyword" type="text" size="20"><input type="submit" value="Go"></p></form><p style="text-align: left;"><img alt="University of Nebraska - Lincoln" src="images/unl.gif"></p></div>

</body></html>
